/**
 * MT-004 (v0): Planner.
 *
 * Converts a validated manifest + index snapshot into an ordered plan of
 * steps and PR metadata. Receives an adapter *instance* (never a provider
 * name) so providers swap without planner changes. The adapter proposes a
 * step outline; the planner constrains every step to the manifest's
 * allowed_actions and applies the approval policy. Staged diff generation
 * lands later in MT-004.
 */
import { searchIndex } from './indexer.js';

const SIDE_EFFECT_ACTIONS = new Set(['git', 'install_deps', 'mcp_call', 'write']);

/**
 * @param {object} manifest - validated microtask/v1 manifest
 * @param {object} snapshot - index snapshot from indexWorkspace()
 * @param {{ name: string, complete: Function }} adapter - provider adapter instance
 * @returns {Promise<{ plan: object, prMetadata: object }>}
 */
export async function planMicrotask(manifest, snapshot, adapter) {
  if (!manifest || manifest.schema !== 'microtask/v1') {
    throw new Error('planMicrotask requires a validated microtask/v1 manifest');
  }
  if (!adapter || typeof adapter.complete !== 'function') {
    throw new Error('planMicrotask requires an adapter instance with complete()');
  }

  const contextFiles = searchIndex(snapshot, `${manifest.title} ${manifest.goal}`).slice(0, 10);

  const completion = await adapter.complete({
    system: 'You are the OpenAgent planner. Produce a short ordered list of concrete steps.',
    prompt: `Goal: ${manifest.goal}\nAllowed actions: ${manifest.allowed_actions.join(', ')}`,
    context: { files: contextFiles, stats: snapshot.stats },
  });

  const proposed = extractSteps(completion.text, manifest);
  const requireApproval = manifest.approval_policy !== 'auto';

  const steps = proposed.map((step, i) => ({
    order: i + 1,
    action: step.action,
    target: step.target,
    rationale: step.rationale,
    requires_approval:
      manifest.approval_policy === 'require_approval_for_all' ||
      (requireApproval && SIDE_EFFECT_ACTIONS.has(step.action)),
  }));

  const plan = {
    schema: 'openagent-plan/v1',
    microtask_id: manifest.id,
    goal: manifest.goal,
    adapter: adapter.name,
    model: completion.model ?? null,
    created_at: new Date().toISOString(),
    context_files: contextFiles,
    steps,
    security: manifest.security,
  };

  const prMetadata = {
    schema: 'openagent-pr/v1',
    branch: `feat/${manifest.id.toLowerCase()}-${slugify(manifest.title)}`,
    title: `${manifest.id}: ${manifest.title}`,
    body: [
      `## Goal`,
      manifest.goal,
      ``,
      `## Plan`,
      ...steps.map((s) => `${s.order}. [${s.action}] ${s.target} — ${s.rationale}${s.requires_approval ? ' *(requires approval)*' : ''}`),
      ``,
      `Generated by openagent-cli (adapter: ${adapter.name}).`,
    ].join('\n'),
    labels: ['agent-generated', manifest.id],
    checklist: ['tests', 'lint', 'security_scan', 'agents_md_updated_if_applicable'],
  };

  return { plan, prMetadata };
}

/**
 * Parse adapter output into steps, constrained to the manifest's
 * allowed_actions. Adapter lines look like: "action: target — rationale".
 * Anything unparseable or disallowed degrades to a safe read/review step.
 */
function extractSteps(text, manifest) {
  const allowed = new Set(manifest.allowed_actions);
  const lines = String(text ?? '')
    .split('\n')
    .map((l) => l.replace(/^\s*(?:\d+[.)]|[-*])\s*/, '').trim())
    .filter(Boolean);

  const steps = [];
  for (const line of lines) {
    const match = line.match(/^([a-z_]+)\s*:\s*([^—-]+?)\s*(?:[—-]\s*(.+))?$/);
    if (match && allowed.has(match[1])) {
      steps.push({ action: match[1], target: match[2].trim(), rationale: match[3]?.trim() ?? 'proposed by adapter' });
    }
  }

  if (steps.length === 0) {
    // Deterministic fallback keeps the pipeline honest even with a bad adapter response.
    const primaryTarget = manifest.inputs?.target_files?.[0] ?? manifest.inputs?.workspace ?? '.';
    steps.push({ action: 'read', target: String(primaryTarget), rationale: 'review context before editing' });
    if (allowed.has('write')) {
      steps.push({ action: 'write', target: String(primaryTarget), rationale: manifest.goal.slice(0, 120) });
    }
    if (allowed.has('run_tests')) {
      steps.push({ action: 'run_tests', target: 'npm test', rationale: 'verify the change' });
    }
  }
  return steps;
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40);
}
